
services:
  backend:

    build: ./backend
    container_name: swayatra-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      swayatra-db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: swayatra-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  swayatra-db:
    image: mysql:8
    container_name: swayatra-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: swayatra
    ports:
     - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
